name: CI
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm ci
      - name: npm test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
      - name: build and release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
